version: '3'
services:
  app:
    image: node:20-alpine
    container_name: vite-react-app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
